# Generated by Django 5.2 on 2025-04-28 20:18

from django.db import migrations


def add_age_group(apps, schema_editor):
    PersonModel = apps.get_model("main_app", "Person")
    people = PersonModel.objects.all()

    for person in people:
        if person.age <= 12:
            person.age_group = "Child"
        elif person.age <= 17:
            person.age_group = "Teen"
        else:
            person.age_group = "Adult"
        person.save()


def set_default_age_group(apps, schema_editor):
    PersonModel = apps.get_model("main_app", "Person")
    default_age_group = PersonModel._meta.get_field("age_group").default

    for person in PersonModel.objects.all():
        person.age_group = default_age_group
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(
            code=add_age_group, 
            reverse_code=set_default_age_group,
            ),
    ]
