# Generated by Django 5.2 on 2025-04-28 23:12

from django.db import migrations


def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")
    phone_devices = SmartphoneModel.objects.all()

    for phone in phone_devices:
        new_price = len(phone.brand) * 120
        phone.price = new_price
        phone.save()


def reset_price(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")
    phone_devices = SmartphoneModel.objects.all()

    for phone in phone_devices:
        phone.price = 0
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            code=set_price,
            reverse_code=reset_price,
        ),
    ]
