# Generated by Django 5.2 on 2025-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_created_on_product_last_edited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='Unknown Supplier', max_length=150),
        ),
    ]
