# Generated by Django 5.2 on 2025-04-28 21:13

from django.db import migrations


def add_rarity(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")
    items = ItemModel.objects.all()

    for item in items:
        if item.price <= 10:
            item.rarity = "Rare"
        elif item.price <= 20:
            item.rarity = "Very Rare"
        elif item.price <= 30:
            item.rarity = "Extremely Rare"
        else:
            item.rarity = "Mega Rare"
        item.save()


def set_rarity_default_value(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")
    items = ItemModel.objects.all()

    for item in items:
        item.rarity = "No rarity"
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(
            code=add_rarity,
            reverse_code=set_rarity_default_value,
        ),
    ]
