# Generated by Django 5.2 on 2025-04-28 23:15

from django.db import migrations


def set_category(apps, schema_editor):
    SmarphoneModel = apps.get_model("main_app", "Smartphone")
    phone_devices = SmarphoneModel.objects.all()

    for phone in phone_devices:
        if phone.price < 750:
            phone.category = "Cheap"
        else:
            phone.category = "Expensive"
        phone.save()


def reset_category(apps, schema_editor):
    SmarphoneModel = apps.get_model("main_app", "Smartphone")
    phone_devices = SmarphoneModel.objects.all()

    for phone in phone_devices:
        phone.category = "No category"
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_smartphone_set_prices'),
    ]

    operations = [
        migrations.RunPython(
            code=set_category,
            reverse_code=reset_category,
        ),
    ]
