# Generated by Django 5.2 on 2025-04-27 13:38
import random

from django.db import migrations


def generate_barcodes(apps, schema_editor):
    Product = apps.get_model("main_app", "Product")
    for product in Product.objects.all():
        product.barcode = random.randint(100_000_000, 1_000_000_000)
        product.save()


def remove_barcodes(apps, schema_editor):
    Product = apps.get_model("main_app", "Product")
    for product in Product.objects.all():
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_barcode'),
    ]

    operations = [
        migrations.RunPython(generate_barcodes, reverse_code=remove_barcodes)
    ]
