# Generated by Django 5.2 on 2025-04-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_exercise_product_recipe_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='duration_in_minutes',
            new_name='duration_minutes',
        ),
    ]
