# Generated by Django 5.2 on 2025-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='operation_system',
            field=models.CharField(choices=[('Windows', 'Windows'), ('MacOS', 'MacOS'), ('Linux', 'Linux'), ('ChromeOS', 'ChromeOS')], max_length=100),
        ),
    ]
