# Generated by Django 5.2 on 2025-04-28 21:48

from django.db import migrations


def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")
    phone_devices = SmartphoneModel.objects.all()

    for phone in phone_devices:
        new_price = len(phone.brand) * 120
        phone.price = new_price
        phone.save()


def set_category(apps, schema_editor):
    SmarphoneModel = apps.get_model("main_app", "Smartphone")
    phone_devices = SmarphoneModel.objects.all()

    for phone in phone_devices:
        if phone.price < 750:
            phone.category = "Cheap"
        else:
            phone.category = "Expensive"
        phone.save()


def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reset_price(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")
    phone_devices = SmartphoneModel.objects.all()

    for phone in phone_devices:
        phone.price = 0
        phone.save()


def reset_category(apps, schema_editor):
    SmarphoneModel = apps.get_model("main_app", "Smartphone")
    phone_devices = SmarphoneModel.objects.all()

    for phone in phone_devices:
        phone.category = "No category"


def reset_price_and_category(apps, schema_editor):
    reset_price(apps, schema_editor)
    reset_category(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            code=set_price_and_category,
            reverse_code=reset_price_and_category,
        ),
    ]
