# Generated by Django 5.2 on 2025-04-29 10:37

from django.db import migrations
from django.utils.timezone import timedelta


def update_orders(apps, schema_editor):
    OrderModel = apps.get_model("main_app", "Order")
    orders = OrderModel.objects.all()

    pending_orders = OrderModel.objects.filter(status="Pending")
    completed_orders = OrderModel.objects.filter(status="Completed")
    cancelled_orders = OrderModel.objects.filter(status="Cancelled")

    for order in pending_orders:
        order.delivery = order.order_date + timedelta(days=3)
        order.save()

    for order in completed_orders:
        order.warranty = "24 months"
        order.save()

    cancelled_orders.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_order_product_name'),
    ]

    operations = [
        migrations.RunPython(
            code=update_orders,
            reverse_code=noop,
        ),
    ]
