# Generated by Django 5.0.4 on 2024-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='calories_burnt',
            new_name='calories_burned',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
