# Generated by Django 5.0.4 on 2024-10-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_calories_burnt_exercise_calories_burned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(),
        ),
    ]
